In [184]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [185]:
# read log file from test RALIS and create pandas dataframe

In [186]:
# path to logs
path = '/mnt/qb/baumgartner/cschmidt77_data/exp2_3Devaluation_RALIS_test/'

In [187]:
exp_2_acdc_ralis_test = os.listdir(path)

In [188]:
exp2_acdc_test_ralis = [exp for exp in exp_2_acdc_ralis_test if 'test' in exp]

In [189]:
data_frame_lists = []
for exp in exp2_acdc_test_ralis: 
    exp_path = path + exp + '/Mean_3D_DSC.txt'
    if os.path.isfile(exp_path): 
        names = ["Mean DSC", "background", "RV", "MYO", "LV", "Experiment", "Augmentation", "lr", "seed", "budget"]
        data = pd.read_csv(exp_path, nrows=1, skiprows=1, names=names, sep ='\t')
        data["Experiment"] = exp
        data = data[["Experiment", "Augmentation", "lr", "seed", "budget", "Mean DSC", "background", "RV", "MYO", "LV"]]
        if 'RIRD' in exp:
            data['Augmentation'] = 'RI/RD' 
        elif 'std' in exp:
            data['Augmentation'] = 'standard' 
        else:
            print("check for augmentation")
        if 'lr_0.01' in exp:
            data['lr'] = '0.01'
        elif 'lr_0.05' in exp:
            data['lr'] = '0.05'
        else:
            print("check for learning rate")
        #if 'ImageNet' in exp:
        #    data["pre-trained"] = 'ImageNet'
        #else:
        #    data["pre-trained"] = '-'
        data['budget'] = exp.split('_')[-3]    
        data['seed'] = exp.split('_')[-1]
        data_frame_lists.append(data)

frame = pd.concat(data_frame_lists, axis=0, ignore_index=True)

In [190]:
frame

,Experiment,Augmentation,lr,seed,budget,Mean DSC,background,RV,MYO,LV
0,2021-10-11-acdc_test_ep49_RIRD_ImageNetBackbon...,RI/RD,0.01,123,1184,0.854,0.996,0.764,0.767,0.891
1,2021-10-11-acdc_test_ep49_RIRD_ImageNetBackbon...,RI/RD,0.01,20,1184,0.838,0.995,0.716,0.746,0.895
2,2021-10-11-acdc_test_ep49_RIRD_ImageNetBackbon...,RI/RD,0.01,234,1184,0.849,0.995,0.787,0.728,0.887
3,2021-10-11-acdc_test_ep49_RIRD_ImageNetBackbon...,RI/RD,0.01,55,1184,0.870,0.996,0.827,0.754,0.905
4,2021-10-11-acdc_test_ep49_RIRD_ImageNetBackbon...,RI/RD,0.01,77,1184,0.858,0.996,0.805,0.747,0.885
...,...,...,...,...,...,...,...,...,...,...
175,2021-10-11-acdc_test_ep49_stdAug_ImageNetBackb...,standard,0.05,123,960,0.826,0.994,0.713,0.722,0.875
176,2021-10-11-acdc_test_ep49_stdAug_ImageNetBackb...,standard,0.05,20,960,0.872,0.996,0.791,0.788,0.914
177,2021-10-11-acdc_test_ep49_stdAug_ImageNetBackb...,standard,0.05,234,960,0.856,0.995,0.768,0.762,0.897
178,2021-10-11-acdc_test_ep49_stdAug_ImageNetBackb...,standard,0.05,55,960,0.828,0.994,0.758,0.692,0.867
179,2021-10-11-acdc_test_ep49_stdAug_ImageNetBackb...,standard,0.05,77,960,0.816,0.993,0.718,0.701,0.854

In [191]:
frame_new = frame.drop(columns="Experiment")

In [192]:
pd.options.display.float_format = "{:,.3f}".format

In [193]:
frame_new.sort_values(by=['Mean DSC'], ascending=False)

    Augmentation    lr seed budget  Mean DSC  background    RV   MYO    LV
160     standard  0.05  123   3568     0.916       0.998 0.873 0.862 0.932
163     standard  0.05   55   3568     0.914       0.997 0.861 0.861 0.936
162     standard  0.05  234   3568     0.913       0.997 0.865 0.860 0.929
161     standard  0.05   20   3568     0.913       0.997 0.861 0.860 0.931
155     standard  0.05  123   2384     0.908       0.997 0.862 0.852 0.922
..           ...   ...  ...    ...       ...         ...   ...   ...   ...
54         RI/RD  0.05   77    128     0.352       0.982 0.000 0.000 0.427
83         RI/RD  0.05   55     64     0.350       0.984 0.105 0.000 0.311
127     standard  0.01  234     64     0.323       0.986 0.000 0.000 0.305
128     standard  0.01   55     64     0.293       0.981 0.123 0.000 0.068
81         RI/RD  0.05   20     64     0.261       0.980 0.000 0.000 0.066

[180 rows x 9 columns]

## ImageNet - stdAug - lr 0.01

In [194]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_std01_budget = frame_new.loc[(frame_new['Augmentation'] == 'standard') & (frame_new['lr'] == '0.01') & (frame_new['budget'] == budget)]
    globals()['imgStd01_meanstd_budget_%s' % budget] = df_img_std01_budget.groupby(['Augmentation','lr', 'budget']).agg({'Mean DSC': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'RV':['mean', 'std'], 'MYO':['mean', 'std'], 'LV':['mean', 'std']})

In [195]:
imgStd01_meanstd_budget_128

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
standard     0.01 128       0.621 0.100      0.990 0.001 0.433 0.158 0.360

                                  LV
                           std  mean   std
Augmentation lr   budget
standard     0.01 128    0.200 0.701 0.061

## ImageNet - stdAug - lr 0.05

In [196]:
for budget in frame_new['budget'].unique():
    df_img_std05_budget = frame_new.loc[(frame_new['Augmentation'] == 'standard') & (frame_new['lr'] == '0.05') & (frame_new['budget'] == budget)]
    globals()['imgStd05_meanstd_budget_%s' % budget] = df_img_std05_budget.groupby(['Augmentation','lr', 'budget']).agg({'Mean DSC': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'RV':['mean', 'std'], 'MYO':['mean', 'std'], 'LV':['mean', 'std']})

## ImageNet - RI/RD Aug - lr 0.05

In [197]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_rird05_budget = frame_new.loc[(frame_new['Augmentation'] == 'RI/RD') & (frame_new['lr'] == '0.05') & (frame_new['budget'] == budget)]
    globals()['imgRIRD05_meanstd_budget_%s' % budget] = df_img_rird05_budget.groupby(['Augmentation','lr', 'budget']).agg({'Mean DSC': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'RV':['mean', 'std'], 'MYO':['mean', 'std'], 'LV':['mean', 'std']})

In [198]:
imgRIRD05_meanstd_budget_592

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
RI/RD        0.05 592       0.748 0.043      0.992 0.001 0.629 0.049 0.573

                                  LV
                           std  mean   std
Augmentation lr   budget
RI/RD        0.05 592    0.084 0.798 0.064

## ImageNet - RI/RD Aug - lr 0.01

In [199]:
for budget in frame_new['budget'].unique():
    # create data frames for different budgets names e.g. imgStd01_budget_128
    df_img_rird01_budget = frame_new.loc[(frame_new['Augmentation'] == 'RI/RD') & (frame_new['lr'] == '0.01') & (frame_new['budget'] == budget)]
    globals()['imgRIRD01_meanstd_budget_%s' % budget] = df_img_rird01_budget.groupby(['Augmentation','lr', 'budget']).agg({'Mean DSC': ['mean', 'std'], 'background': ['mean', 'std'],
                                                          'RV':['mean', 'std'], 'MYO':['mean', 'std'], 'LV':['mean', 'std']})

## Concatenated for budgets (ImageNet - RI/RD Aug - lr 0.05)

In [200]:
# budgets 64 128 592 960 1184 1424 1904 2384 3568

In [201]:
budgets = frame_new['budget'].unique()

In [202]:
budgets

array(['1184', '128', '1424', '1904', '2384', '3568', '592', '64', '960'],
      dtype=object)

In [203]:
df_img_rird_05 = pd.concat([imgRIRD05_meanstd_budget_64, imgRIRD05_meanstd_budget_128, imgRIRD05_meanstd_budget_592,
                           imgRIRD05_meanstd_budget_960, imgRIRD05_meanstd_budget_1184, imgRIRD05_meanstd_budget_1424,
                           imgRIRD05_meanstd_budget_1904, imgRIRD05_meanstd_budget_2384, imgRIRD05_meanstd_budget_3568])

In [204]:
df_img_rird_05

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
RI/RD        0.05 64        0.417 0.129      0.984 0.003 0.194 0.256 0.115
                  128       0.608 0.146      0.988 0.003 0.422 0.240 0.379
                  592       0.748 0.043      0.992 0.001 0.629 0.049 0.573
                  960       0.807 0.033      0.994 0.001 0.702 0.100 0.676
                  1184      0.849 0.007      0.995 0.000 0.765 0.028 0.748
                  1424      0.873 0.009      0.996 0.000 0.810 0.028 0.779
                  1904      0.891 0.002      0.997 0.000 0.836 0.019 0.816
                  2384      0.900 0.007      0.997 0.000 0.848 0.012 0.837
                  3568      0.902 0.006      0.997 0.000 0.848 0.010 0.845

                                  LV
                           std  mean   std
Augmentation lr   budget
RI/RD        0.05 64     0.145 0.375 0.201
                  128    0.224 0.643 0.149
                  592    0.084 0.798 0.064
                  960    0.037 0.855 0.030
                  1184   0.025 0.889 0.012
                  1424   0.014 0.908 0.006
                  1904   0.013 0.915 0.004
                  2384   0.017 0.918 0.009
                  3568   0.012 0.918 0.008

## Concatenated for budgets (ImageNet - RI/RD Aug - lr 0.01)

In [205]:
df_img_rird_01 = pd.concat([imgRIRD01_meanstd_budget_64, imgRIRD01_meanstd_budget_128, imgRIRD01_meanstd_budget_592,
                           imgRIRD01_meanstd_budget_960, imgRIRD01_meanstd_budget_1184, imgRIRD01_meanstd_budget_1424,
                           imgRIRD01_meanstd_budget_1904, imgRIRD01_meanstd_budget_2384, imgRIRD01_meanstd_budget_3568])

In [206]:
df_img_rird_01

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
RI/RD        0.01 64        0.485 0.088      0.988 0.001 0.328 0.190 0.076
                  128       0.553 0.110      0.988 0.003 0.327 0.259 0.218
                  592       0.795 0.028      0.993 0.001 0.707 0.028 0.637
                  960       0.834 0.007      0.995 0.000 0.753 0.021 0.712
                  1184      0.854 0.012      0.996 0.001 0.780 0.042 0.748
                  1424      0.870 0.006      0.996 0.000 0.800 0.016 0.778
                  1904      0.891 0.003      0.997 0.000 0.833 0.016 0.815
                  2384      0.896 0.005      0.997 0.000 0.836 0.014 0.831
                  3568      0.898 0.004      0.997 0.000 0.843 0.011 0.830

                                  LV
                           std  mean   std
Augmentation lr   budget
RI/RD        0.01 64     0.140 0.547 0.095
                  128    0.225 0.679 0.089
                  592    0.054 0.845 0.039
                  960    0.026 0.874 0.021
                  1184   0.014 0.892 0.008
                  1424   0.009 0.904 0.006
                  1904   0.008 0.917 0.002
                  2384   0.007 0.920 0.001
                  3568   0.004 0.920 0.004

## Concatenated for budgets (ImageNet - std Aug - lr 0.01)

In [207]:
df_img_std_01 = pd.concat([imgStd01_meanstd_budget_64, imgStd01_meanstd_budget_128, imgStd01_meanstd_budget_592,
                           imgStd01_meanstd_budget_960, imgStd01_meanstd_budget_1184, imgStd01_meanstd_budget_1424,
                           imgStd01_meanstd_budget_1904, imgStd01_meanstd_budget_2384, imgStd01_meanstd_budget_3568])

In [208]:
df_img_std_01

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
standard     0.01 64        0.404 0.136      0.987 0.003 0.106 0.177 0.081
                  128       0.621 0.100      0.990 0.001 0.433 0.158 0.360
                  592       0.810 0.025      0.994 0.001 0.711 0.062 0.677
                  960       0.848 0.014      0.995 0.001 0.758 0.022 0.749
                  1184      0.857 0.025      0.996 0.001 0.788 0.046 0.753
                  1424      0.880 0.003      0.996 0.000 0.817 0.015 0.797
                  1904      0.898 0.001      0.997 0.000 0.846 0.006 0.828
                  2384      0.903 0.003      0.997 0.000 0.849 0.007 0.842
                  3568      0.900 0.007      0.997 0.000 0.843 0.018 0.837

                                  LV
                           std  mean   std
Augmentation lr   budget
standard     0.01 64     0.181 0.440 0.260
                  128    0.200 0.701 0.061
                  592    0.029 0.857 0.021
                  960    0.021 0.888 0.021
                  1184   0.043 0.893 0.017
                  1424   0.007 0.911 0.004
                  1904   0.004 0.920 0.003
                  2384   0.004 0.923 0.004
                  3568   0.008 0.921 0.004

## Concatenated for budgets (ImageNet - std Aug - lr 0.05)

In [209]:
df_img_std_05 = pd.concat([imgStd05_meanstd_budget_64, imgStd05_meanstd_budget_128, imgStd05_meanstd_budget_592,
                           imgStd05_meanstd_budget_960, imgStd05_meanstd_budget_1184, imgStd05_meanstd_budget_1424,
                           imgStd05_meanstd_budget_1904, imgStd05_meanstd_budget_2384, imgStd05_meanstd_budget_3568])

In [210]:
df_img_std_05

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
standard     0.05 64        0.521 0.109      0.987 0.003 0.285 0.257 0.211
                  128       0.662 0.052      0.989 0.002 0.538 0.046 0.469
                  592       0.796 0.015      0.993 0.000 0.672 0.071 0.669
                  960       0.840 0.023      0.995 0.001 0.749 0.034 0.733
                  1184      0.851 0.020      0.995 0.001 0.756 0.048 0.763
                  1424      0.881 0.006      0.996 0.000 0.814 0.016 0.807
                  1904      0.894 0.014      0.997 0.001 0.838 0.025 0.828
                  2384      0.903 0.006      0.997 0.000 0.849 0.011 0.845
                  3568      0.911 0.006      0.997 0.000 0.862 0.008 0.857

                                  LV
                           std  mean   std
Augmentation lr   budget
standard     0.05 64     0.166 0.601 0.149
                  128    0.112 0.651 0.098
                  592    0.017 0.849 0.016
                  960    0.041 0.881 0.024
                  1184   0.030 0.891 0.016
                  1424   0.023 0.909 0.009
                  1904   0.022 0.914 0.011
                  2384   0.011 0.921 0.004
                  3568   0.008 0.929 0.008

In [211]:
df_img_std_05

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
standard     0.05 64        0.521 0.109      0.987 0.003 0.285 0.257 0.211
                  128       0.662 0.052      0.989 0.002 0.538 0.046 0.469
                  592       0.796 0.015      0.993 0.000 0.672 0.071 0.669
                  960       0.840 0.023      0.995 0.001 0.749 0.034 0.733
                  1184      0.851 0.020      0.995 0.001 0.756 0.048 0.763
                  1424      0.881 0.006      0.996 0.000 0.814 0.016 0.807
                  1904      0.894 0.014      0.997 0.001 0.838 0.025 0.828
                  2384      0.903 0.006      0.997 0.000 0.849 0.011 0.845
                  3568      0.911 0.006      0.997 0.000 0.862 0.008 0.857

                                  LV
                           std  mean   std
Augmentation lr   budget
standard     0.05 64     0.166 0.601 0.149
                  128    0.112 0.651 0.098
                  592    0.017 0.849 0.016
                  960    0.041 0.881 0.024
                  1184   0.030 0.891 0.016
                  1424   0.023 0.909 0.009
                  1904   0.022 0.914 0.011
                  2384   0.011 0.921 0.004
                  3568   0.008 0.929 0.008

In [212]:
## Concatenate for all 4 settings (lr 0.01 and lr 0.05) and (std and rird augmentations)

In [213]:
df_lr_01 = pd.concat([df_img_rird_01, df_img_std_01])

In [214]:
df_lr_01

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
RI/RD        0.01 64        0.485 0.088      0.988 0.001 0.328 0.190 0.076
                  128       0.553 0.110      0.988 0.003 0.327 0.259 0.218
                  592       0.795 0.028      0.993 0.001 0.707 0.028 0.637
                  960       0.834 0.007      0.995 0.000 0.753 0.021 0.712
                  1184      0.854 0.012      0.996 0.001 0.780 0.042 0.748
                  1424      0.870 0.006      0.996 0.000 0.800 0.016 0.778
                  1904      0.891 0.003      0.997 0.000 0.833 0.016 0.815
                  2384      0.896 0.005      0.997 0.000 0.836 0.014 0.831
                  3568      0.898 0.004      0.997 0.000 0.843 0.011 0.830
standard     0.01 64        0.404 0.136      0.987 0.003 0.106 0.177 0.081
                  128       0.621 0.100      0.990 0.001 0.433 0.158 0.360
                  592       0.810 0.025      0.994 0.001 0.711 0.062 0.677
                  960       0.848 0.014      0.995 0.001 0.758 0.022 0.749
                  1184      0.857 0.025      0.996 0.001 0.788 0.046 0.753
                  1424      0.880 0.003      0.996 0.000 0.817 0.015 0.797
                  1904      0.898 0.001      0.997 0.000 0.846 0.006 0.828
                  2384      0.903 0.003      0.997 0.000 0.849 0.007 0.842
                  3568      0.900 0.007      0.997 0.000 0.843 0.018 0.837

                                  LV
                           std  mean   std
Augmentation lr   budget
RI/RD        0.01 64     0.140 0.547 0.095
                  128    0.225 0.679 0.089
                  592    0.054 0.845 0.039
                  960    0.026 0.874 0.021
                  1184   0.014 0.892 0.008
                  1424   0.009 0.904 0.006
                  1904   0.008 0.917 0.002
                  2384   0.007 0.920 0.001
                  3568   0.004 0.920 0.004
standard     0.01 64     0.181 0.440 0.260
                  128    0.200 0.701 0.061
                  592    0.029 0.857 0.021
                  960    0.021 0.888 0.021
                  1184   0.043 0.893 0.017
                  1424   0.007 0.911 0.004
                  1904   0.004 0.920 0.003
                  2384   0.004 0.923 0.004
                  3568   0.008 0.921 0.004

In [215]:
df_lr_01.columns

MultiIndex([(  'Mean DSC', 'mean'),
            (  'Mean DSC',  'std'),
            ('background', 'mean'),
            ('background',  'std'),
            (        'RV', 'mean'),
            (        'RV',  'std'),
            (       'MYO', 'mean'),
            (       'MYO',  'std'),
            (        'LV', 'mean'),
            (        'LV',  'std')],
           )

In [216]:
df_lr_01

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
RI/RD        0.01 64        0.485 0.088      0.988 0.001 0.328 0.190 0.076
                  128       0.553 0.110      0.988 0.003 0.327 0.259 0.218
                  592       0.795 0.028      0.993 0.001 0.707 0.028 0.637
                  960       0.834 0.007      0.995 0.000 0.753 0.021 0.712
                  1184      0.854 0.012      0.996 0.001 0.780 0.042 0.748
                  1424      0.870 0.006      0.996 0.000 0.800 0.016 0.778
                  1904      0.891 0.003      0.997 0.000 0.833 0.016 0.815
                  2384      0.896 0.005      0.997 0.000 0.836 0.014 0.831
                  3568      0.898 0.004      0.997 0.000 0.843 0.011 0.830
standard     0.01 64        0.404 0.136      0.987 0.003 0.106 0.177 0.081
                  128       0.621 0.100      0.990 0.001 0.433 0.158 0.360
                  592       0.810 0.025      0.994 0.001 0.711 0.062 0.677
                  960       0.848 0.014      0.995 0.001 0.758 0.022 0.749
                  1184      0.857 0.025      0.996 0.001 0.788 0.046 0.753
                  1424      0.880 0.003      0.996 0.000 0.817 0.015 0.797
                  1904      0.898 0.001      0.997 0.000 0.846 0.006 0.828
                  2384      0.903 0.003      0.997 0.000 0.849 0.007 0.842
                  3568      0.900 0.007      0.997 0.000 0.843 0.018 0.837

                                  LV
                           std  mean   std
Augmentation lr   budget
RI/RD        0.01 64     0.140 0.547 0.095
                  128    0.225 0.679 0.089
                  592    0.054 0.845 0.039
                  960    0.026 0.874 0.021
                  1184   0.014 0.892 0.008
                  1424   0.009 0.904 0.006
                  1904   0.008 0.917 0.002
                  2384   0.007 0.920 0.001
                  3568   0.004 0.920 0.004
standard     0.01 64     0.181 0.440 0.260
                  128    0.200 0.701 0.061
                  592    0.029 0.857 0.021
                  960    0.021 0.888 0.021
                  1184   0.043 0.893 0.017
                  1424   0.007 0.911 0.004
                  1904   0.004 0.920 0.003
                  2384   0.004 0.923 0.004
                  3568   0.008 0.921 0.004

In [217]:
cols = [i for i in df_lr_01.columns.values]
cols = np.unique(cols)
idx = [2,4,3,0,1]
cols = cols[idx]

In [218]:
df_new = pd.DataFrame(columns=cols)
for c in cols:
    means = df_lr_01[c]['mean'].values
    stds = df_lr_01[c]['std'].values
    newcol = [f'{mean:.3f}(Â±{std:.3f})' for mean, std in zip(means, stds)]
    df_new[c] = newcol
    df_lr_01.drop(c, axis=1, inplace=True)
    df_lr_01[c] = newcol

/home/carina/.local/lib/python3.8/site-packages/pandas/core/generic.py:4153: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)

In [219]:
df_lr_01

                               Mean DSC     background             RV  \

Augmentation lr   budget
RI/RD        0.01 64      0.485(Â±0.088)  0.988(Â±0.001)  0.328(Â±0.190)
                  128     0.553(Â±0.110)  0.988(Â±0.003)  0.327(Â±0.259)
                  592     0.795(Â±0.028)  0.993(Â±0.001)  0.707(Â±0.028)
                  960     0.834(Â±0.007)  0.995(Â±0.000)  0.753(Â±0.021)
                  1184    0.854(Â±0.012)  0.996(Â±0.001)  0.780(Â±0.042)
                  1424    0.870(Â±0.006)  0.996(Â±0.000)  0.800(Â±0.016)
                  1904    0.891(Â±0.003)  0.997(Â±0.000)  0.833(Â±0.016)
                  2384    0.896(Â±0.005)  0.997(Â±0.000)  0.836(Â±0.014)
                  3568    0.898(Â±0.004)  0.997(Â±0.000)  0.843(Â±0.011)
standard     0.01 64      0.404(Â±0.136)  0.987(Â±0.003)  0.106(Â±0.177)
                  128     0.621(Â±0.100)  0.990(Â±0.001)  0.433(Â±0.158)
                  592     0.810(Â±0.025)  0.994(Â±0.001)  0.711(Â±0.062)
                  960     0.848(Â±0.014)  0.995(Â±0.001)  0.758(Â±0.022)
                  1184    0.857(Â±0.025)  0.996(Â±0.001)  0.788(Â±0.046)
                  1424    0.880(Â±0.003)  0.996(Â±0.000)  0.817(Â±0.015)
                  1904    0.898(Â±0.001)  0.997(Â±0.000)  0.846(Â±0.006)
                  2384    0.903(Â±0.003)  0.997(Â±0.000)  0.849(Â±0.007)
                  3568    0.900(Â±0.007)  0.997(Â±0.000)  0.843(Â±0.018)

                                     LV            MYO

Augmentation lr   budget
RI/RD        0.01 64      0.547(Â±0.095)  0.076(Â±0.140)
                  128     0.679(Â±0.089)  0.218(Â±0.225)
                  592     0.845(Â±0.039)  0.637(Â±0.054)
                  960     0.874(Â±0.021)  0.712(Â±0.026)
                  1184    0.892(Â±0.008)  0.748(Â±0.014)
                  1424    0.904(Â±0.006)  0.778(Â±0.009)
                  1904    0.917(Â±0.002)  0.815(Â±0.008)
                  2384    0.920(Â±0.001)  0.831(Â±0.007)
                  3568    0.920(Â±0.004)  0.830(Â±0.004)
standard     0.01 64      0.440(Â±0.260)  0.081(Â±0.181)
                  128     0.701(Â±0.061)  0.360(Â±0.200)
                  592     0.857(Â±0.021)  0.677(Â±0.029)
                  960     0.888(Â±0.021)  0.749(Â±0.021)
                  1184    0.893(Â±0.017)  0.753(Â±0.043)
                  1424    0.911(Â±0.004)  0.797(Â±0.007)
                  1904    0.920(Â±0.003)  0.828(Â±0.004)
                  2384    0.923(Â±0.004)  0.842(Â±0.004)
                  3568    0.921(Â±0.004)  0.837(Â±0.008)

In [233]:
del df_lr_01['background']
df_lr_01 = df_lr_01.rename(columns={"Mean DSC":"All Classes"})

In [234]:
print(df_lr_01.to_latex(index=True))

\begin{tabular}{lllllll}
\toprule
         &      &      &    All Classes &             RV &             LV &            MYO \\
         &      &      \\
Augmentation & lr & budget &                &                &                &                \\
\midrule
RI/RD & 0.01 & 64 &  0.485(Â±0.088) &  0.328(Â±0.190) &  0.547(Â±0.095) &  0.076(Â±0.140) \\
         &      & 128 &  0.553(Â±0.110) &  0.327(Â±0.259) &  0.679(Â±0.089) &  0.218(Â±0.225) \\
         &      & 592 &  0.795(Â±0.028) &  0.707(Â±0.028) &  0.845(Â±0.039) &  0.637(Â±0.054) \\
         &      & 960 &  0.834(Â±0.007) &  0.753(Â±0.021) &  0.874(Â±0.021) &  0.712(Â±0.026) \\
         &      & 1184 &  0.854(Â±0.012) &  0.780(Â±0.042) &  0.892(Â±0.008) &  0.748(Â±0.014) \\
         &      & 1424 &  0.870(Â±0.006) &  0.800(Â±0.016) &  0.904(Â±0.006) &  0.778(Â±0.009) \\
         &      & 1904 &  0.891(Â±0.003) &  0.833(Â±0.016) &  0.917(Â±0.002) &  0.815(Â±0.008) \\
         &      & 2384 &  0.896(Â±0.005) &  0.836(Â±0.014) &  0.920(Â±0.001) &  0.831(Â±0.007) \\
         &      & 3568 &  0.898(Â±0.004) &  0.843(Â±0.011) &  0.920(Â±0.004) &  0.830(Â±0.004) \\
standard & 0.01 & 64 &  0.404(Â±0.136) &  0.106(Â±0.177) &  0.440(Â±0.260) &  0.081(Â±0.181) \\
         &      & 128 &  0.621(Â±0.100) &  0.433(Â±0.158) &  0.701(Â±0.061) &  0.360(Â±0.200) \\
         &      & 592 &  0.810(Â±0.025) &  0.711(Â±0.062) &  0.857(Â±0.021) &  0.677(Â±0.029) \\
         &      & 960 &  0.848(Â±0.014) &  0.758(Â±0.022) &  0.888(Â±0.021) &  0.749(Â±0.021) \\
         &      & 1184 &  0.857(Â±0.025) &  0.788(Â±0.046) &  0.893(Â±0.017) &  0.753(Â±0.043) \\
         &      & 1424 &  0.880(Â±0.003) &  0.817(Â±0.015) &  0.911(Â±0.004) &  0.797(Â±0.007) \\
         &      & 1904 &  0.898(Â±0.001) &  0.846(Â±0.006) &  0.920(Â±0.003) &  0.828(Â±0.004) \\
         &      & 2384 &  0.903(Â±0.003) &  0.849(Â±0.007) &  0.923(Â±0.004) &  0.842(Â±0.004) \\
         &      & 3568 &  0.900(Â±0.007) &  0.843(Â±0.018) &  0.921(Â±0.004) &  0.837(Â±0.008) \\
\bottomrule
\end{tabular}

In [247]:
df_lr_05 = pd.concat([df_img_rird_05, df_img_std_05])

In [248]:
cols = [i for i in df_lr_05.columns.values]
cols = np.unique(cols)
idx = [2,4,3,0,1]
cols = cols[idx]

In [249]:
cols

array(['Mean DSC', 'background', 'RV', 'LV', 'MYO'], dtype='<U10')

In [250]:
df_new = pd.DataFrame(columns=cols)
for c in cols:
    means = df_lr_05[c]['mean'].values
    stds = df_lr_05[c]['std'].values
    newcol = [f'{mean:.3f}(Â±{std:.3f})' for mean, std in zip(means, stds)]
    df_new[c] = newcol
    df_lr_05.drop(c, axis=1, inplace=True)
    df_lr_05[c] = newcol
del df_lr_05['background']
df_lr_05 = df_lr_05.rename(columns={"Mean DSC":"All Classes"})

In [251]:
print(df_lr_05.to_latex(index=True))

\begin{tabular}{lllllll}
\toprule
         &      &      &    All Classes &             RV &             LV &            MYO \\
         &      &      \\
Augmentation & lr & budget &                &                &                &                \\
\midrule
RI/RD & 0.05 & 64 &  0.417(Â±0.129) &  0.194(Â±0.256) &  0.375(Â±0.201) &  0.115(Â±0.145) \\
         &      & 128 &  0.608(Â±0.146) &  0.422(Â±0.240) &  0.643(Â±0.149) &  0.379(Â±0.224) \\
         &      & 592 &  0.748(Â±0.043) &  0.629(Â±0.049) &  0.798(Â±0.064) &  0.573(Â±0.084) \\
         &      & 960 &  0.807(Â±0.033) &  0.702(Â±0.100) &  0.855(Â±0.030) &  0.676(Â±0.037) \\
         &      & 1184 &  0.849(Â±0.007) &  0.765(Â±0.028) &  0.889(Â±0.012) &  0.748(Â±0.025) \\
         &      & 1424 &  0.873(Â±0.009) &  0.810(Â±0.028) &  0.908(Â±0.006) &  0.779(Â±0.014) \\
         &      & 1904 &  0.891(Â±0.002) &  0.836(Â±0.019) &  0.915(Â±0.004) &  0.816(Â±0.013) \\
         &      & 2384 &  0.900(Â±0.007) &  0.848(Â±0.012) &  0.918(Â±0.009) &  0.837(Â±0.017) \\
         &      & 3568 &  0.902(Â±0.006) &  0.848(Â±0.010) &  0.918(Â±0.008) &  0.845(Â±0.012) \\
standard & 0.05 & 64 &  0.521(Â±0.109) &  0.285(Â±0.257) &  0.601(Â±0.149) &  0.211(Â±0.166) \\
         &      & 128 &  0.662(Â±0.052) &  0.538(Â±0.046) &  0.651(Â±0.098) &  0.469(Â±0.112) \\
         &      & 592 &  0.796(Â±0.015) &  0.672(Â±0.071) &  0.849(Â±0.016) &  0.669(Â±0.017) \\
         &      & 960 &  0.840(Â±0.023) &  0.749(Â±0.034) &  0.881(Â±0.024) &  0.733(Â±0.041) \\
         &      & 1184 &  0.851(Â±0.020) &  0.756(Â±0.048) &  0.891(Â±0.016) &  0.763(Â±0.030) \\
         &      & 1424 &  0.881(Â±0.006) &  0.814(Â±0.016) &  0.909(Â±0.009) &  0.807(Â±0.023) \\
         &      & 1904 &  0.894(Â±0.014) &  0.838(Â±0.025) &  0.914(Â±0.011) &  0.828(Â±0.022) \\
         &      & 2384 &  0.903(Â±0.006) &  0.849(Â±0.011) &  0.921(Â±0.004) &  0.845(Â±0.011) \\
         &      & 3568 &  0.911(Â±0.006) &  0.862(Â±0.008) &  0.929(Â±0.008) &  0.857(Â±0.008) \\
\bottomrule
\end{tabular}

In [262]:
df_lr_05

                            All Classes             RV             LV  \

Augmentation lr   budget
RI/RD        0.05 64      0.417(Â±0.129)  0.194(Â±0.256)  0.375(Â±0.201)
                  128     0.608(Â±0.146)  0.422(Â±0.240)  0.643(Â±0.149)
                  592     0.748(Â±0.043)  0.629(Â±0.049)  0.798(Â±0.064)
                  960     0.807(Â±0.033)  0.702(Â±0.100)  0.855(Â±0.030)
                  1184    0.849(Â±0.007)  0.765(Â±0.028)  0.889(Â±0.012)
                  1424    0.873(Â±0.009)  0.810(Â±0.028)  0.908(Â±0.006)
                  1904    0.891(Â±0.002)  0.836(Â±0.019)  0.915(Â±0.004)
                  2384    0.900(Â±0.007)  0.848(Â±0.012)  0.918(Â±0.009)
                  3568    0.902(Â±0.006)  0.848(Â±0.010)  0.918(Â±0.008)
standard     0.05 64      0.521(Â±0.109)  0.285(Â±0.257)  0.601(Â±0.149)
                  128     0.662(Â±0.052)  0.538(Â±0.046)  0.651(Â±0.098)
                  592     0.796(Â±0.015)  0.672(Â±0.071)  0.849(Â±0.016)
                  960     0.840(Â±0.023)  0.749(Â±0.034)  0.881(Â±0.024)
                  1184    0.851(Â±0.020)  0.756(Â±0.048)  0.891(Â±0.016)
                  1424    0.881(Â±0.006)  0.814(Â±0.016)  0.909(Â±0.009)
                  1904    0.894(Â±0.014)  0.838(Â±0.025)  0.914(Â±0.011)
                  2384    0.903(Â±0.006)  0.849(Â±0.011)  0.921(Â±0.004)
                  3568    0.911(Â±0.006)  0.862(Â±0.008)  0.929(Â±0.008)

                                    MYO

Augmentation lr   budget
RI/RD        0.05 64      0.115(Â±0.145)
                  128     0.379(Â±0.224)
                  592     0.573(Â±0.084)
                  960     0.676(Â±0.037)
                  1184    0.748(Â±0.025)
                  1424    0.779(Â±0.014)
                  1904    0.816(Â±0.013)
                  2384    0.837(Â±0.017)
                  3568    0.845(Â±0.012)
standard     0.05 64      0.211(Â±0.166)
                  128     0.469(Â±0.112)
                  592     0.669(Â±0.017)
                  960     0.733(Â±0.041)
                  1184    0.763(Â±0.030)
                  1424    0.807(Â±0.023)
                  1904    0.828(Â±0.022)
                  2384    0.845(Â±0.011)
                  3568    0.857(Â±0.008)

In [276]:
len(budgets)

9

In [278]:
len(df_lr_05['All Classes'].values[9:18])

9

In [281]:
allClasses_values = df_lr_05['All Classes'].values[9:18]

In [282]:
allClasses_values

array(['0.521(Â±0.109)', '0.662(Â±0.052)', '0.796(Â±0.015)', '0.840(Â±0.023)',
       '0.851(Â±0.020)', '0.881(Â±0.006)', '0.894(Â±0.014)', '0.903(Â±0.006)',
       '0.911(Â±0.006)'], dtype=object)

In [270]:
df_lr_aug = pd.concat([df_img_rird_01, df_img_rird_05, df_img_std_01, df_img_std_05])

In [271]:
df_lr_aug

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
RI/RD        0.01 64        0.485 0.088      0.988 0.001 0.328 0.190 0.076
                  128       0.553 0.110      0.988 0.003 0.327 0.259 0.218
                  592       0.795 0.028      0.993 0.001 0.707 0.028 0.637
                  960       0.834 0.007      0.995 0.000 0.753 0.021 0.712
                  1184      0.854 0.012      0.996 0.001 0.780 0.042 0.748
                  1424      0.870 0.006      0.996 0.000 0.800 0.016 0.778
                  1904      0.891 0.003      0.997 0.000 0.833 0.016 0.815
                  2384      0.896 0.005      0.997 0.000 0.836 0.014 0.831
                  3568      0.898 0.004      0.997 0.000 0.843 0.011 0.830
             0.05 64        0.417 0.129      0.984 0.003 0.194 0.256 0.115
                  128       0.608 0.146      0.988 0.003 0.422 0.240 0.379
                  592       0.748 0.043      0.992 0.001 0.629 0.049 0.573
                  960       0.807 0.033      0.994 0.001 0.702 0.100 0.676
                  1184      0.849 0.007      0.995 0.000 0.765 0.028 0.748
                  1424      0.873 0.009      0.996 0.000 0.810 0.028 0.779
                  1904      0.891 0.002      0.997 0.000 0.836 0.019 0.816
                  2384      0.900 0.007      0.997 0.000 0.848 0.012 0.837
                  3568      0.902 0.006      0.997 0.000 0.848 0.010 0.845
standard     0.01 64        0.404 0.136      0.987 0.003 0.106 0.177 0.081
                  128       0.621 0.100      0.990 0.001 0.433 0.158 0.360
                  592       0.810 0.025      0.994 0.001 0.711 0.062 0.677
                  960       0.848 0.014      0.995 0.001 0.758 0.022 0.749
                  1184      0.857 0.025      0.996 0.001 0.788 0.046 0.753
                  1424      0.880 0.003      0.996 0.000 0.817 0.015 0.797
                  1904      0.898 0.001      0.997 0.000 0.846 0.006 0.828
                  2384      0.903 0.003      0.997 0.000 0.849 0.007 0.842
                  3568      0.900 0.007      0.997 0.000 0.843 0.018 0.837
             0.05 64        0.521 0.109      0.987 0.003 0.285 0.257 0.211
                  128       0.662 0.052      0.989 0.002 0.538 0.046 0.469
                  592       0.796 0.015      0.993 0.000 0.672 0.071 0.669
                  960       0.840 0.023      0.995 0.001 0.749 0.034 0.733
                  1184      0.851 0.020      0.995 0.001 0.756 0.048 0.763
                  1424      0.881 0.006      0.996 0.000 0.814 0.016 0.807
                  1904      0.894 0.014      0.997 0.001 0.838 0.025 0.828
                  2384      0.903 0.006      0.997 0.000 0.849 0.011 0.845
                  3568      0.911 0.006      0.997 0.000 0.862 0.008 0.857

                                  LV
                           std  mean   std
Augmentation lr   budget
RI/RD        0.01 64     0.140 0.547 0.095
                  128    0.225 0.679 0.089
                  592    0.054 0.845 0.039
                  960    0.026 0.874 0.021
                  1184   0.014 0.892 0.008
                  1424   0.009 0.904 0.006
                  1904   0.008 0.917 0.002
                  2384   0.007 0.920 0.001
                  3568   0.004 0.920 0.004
             0.05 64     0.145 0.375 0.201
                  128    0.224 0.643 0.149
                  592    0.084 0.798 0.064
                  960    0.037 0.855 0.030
                  1184   0.025 0.889 0.012
                  1424   0.014 0.908 0.006
                  1904   0.013 0.915 0.004
                  2384   0.017 0.918 0.009
                  3568   0.012 0.918 0.008
standard     0.01 64     0.181 0.440 0.260
                  128    0.200 0.701 0.061
                  592    0.029 0.857 0.021
                  960    0.021 0.888 0.021
                  1184   0.043 0.893 0.017
                  1424   0.007 0.911 0.004
                  1904   0.004 0.920 0.003
                  2384   0.004 0.923 0.004
                  3568   0.008 0.921 0.004
             0.05 64     0.166 0.601 0.149
                  128    0.112 0.651 0.098
                  592    0.017 0.849 0.016
                  960    0.041 0.881 0.024
                  1184   0.030 0.891 0.016
                  1424   0.023 0.909 0.009
                  1904   0.022 0.914 0.011
                  2384   0.011 0.921 0.004
                  3568   0.008 0.929 0.008

In [ ]:
print(df_lr_aug.to_latex(index=True))

In [ ]:
print(imgNet_Aug_lr.to_latex(index=True))

In [ ]:
print(mean_frame.to_latex(index=False))

In [ ]:
print(frame_new.to_latex(index=False))

In [109]:
df_img_std_05

                         Mean DSC       background          RV         MYO  \
                             mean   std       mean   std  mean   std  mean
Augmentation lr   budget
standard     0.05 64        0.521 0.109      0.987 0.003 0.285 0.257 0.211
                  128       0.662 0.052      0.989 0.002 0.538 0.046 0.469
                  592       0.796 0.015      0.993 0.000 0.672 0.071 0.669
                  960       0.840 0.023      0.995 0.001 0.749 0.034 0.733
                  1184      0.851 0.020      0.995 0.001 0.756 0.048 0.763
                  1424      0.881 0.006      0.996 0.000 0.814 0.016 0.807
                  1904      0.894 0.014      0.997 0.001 0.838 0.025 0.828
                  2384      0.903 0.006      0.997 0.000 0.849 0.011 0.845
                  3568      0.911 0.006      0.997 0.000 0.862 0.008 0.857

                                  LV
                           std  mean   std
Augmentation lr   budget
standard     0.05 64     0.166 0.601 0.149
                  128    0.112 0.651 0.098
                  592    0.017 0.849 0.016
                  960    0.041 0.881 0.024
                  1184   0.030 0.891 0.016
                  1424   0.023 0.909 0.009
                  1904   0.022 0.914 0.011
                  2384   0.011 0.921 0.004
                  3568   0.008 0.929 0.008